### ISSUE TITLE
Add to the Arduino library manager

### ISSUE THREAD

**Issue by jimbobbennett** [Seeed-Studio/Seeed_Arduino_Audio#1]
Can you please add this to the Arduino library manager so it is easier to use from the Arduino IDE and PlatformIO

**Comment by Pillar1989** [comment]
@lakshanthad  pls

**Comment by lakshanthad** [comment]
Hi @jimbobbennett . I have added the library to Arduino library manager. It will take some time to appear in Arduino IDE. 

Please check using **Seeed Arduino Audio** inside Arduino library manager
