### ISSUE TITLE
Library is not showing in PlatformIO

### ISSUE THREAD

**Issue by jimbobbennett** [Seeed-Studio/Seeed_Arduino_Audio#2]
Thanks @lakshanthad for publishing this. I don't see it in the PlatformIO library manager.

https://platformio.org/lib/search?query=seeed%20audio

PlatformIO is very specific about the library.properties file, and in this repo it looks like the email is missing from the maintainer field.

```ini
maintainer=Seeed Studio
```

I would raise a PR to update, but not sure what email to use! Can you update this, then bump the version number and release please.

**Comment by jimbobbennett** [comment]
For reference, this is the  field from a [library that works in PlatformIO](https://github.com/Seeed-Studio/Seeed_Arduino_rpcWiFi):

```ini
maintainer=hongtai.liu(lht856@foxmail.com)
```

**Comment by lakshanthad** [comment]
@jimbobbennett it's done
