### ISSUE TITLE
Audio.h software interrupts creating issues with other main interrupts used by another process. (PubSubClient) 

### ISSUE THREAD

**Issue by gbernal** [Seeed-Studio/Seeed_Arduino_Audio#4]
Hi,

I'm developing a project that looks to play a sound read from an sd card when an mqtt message is received.
I'm using the [Wio Terminal](https://wiki.seeedstudio.com/Wio-Terminal-Getting-Started/) with the [respeaker](https://www.seeedstudio.com/ReSpeaker-2-Mics-Pi-HAT.html?gclid=CjwKCAjwlcaRBhBYEiwAK341jRAffqkIZnlyiQv09UeCWeVKXTKTrPll76iU0jnAd1gsfTEC1RqJexoClT0QAvD_BwE) add on.

After a lot of debugging, I have come to realize that after I run the function .play from the [audio library](https://github.com/Seeed-Studio/Seeed_Arduino_Audio) everything freezes and I have to power cycle to be able to load the code. If I remove client.loop() and I pressed a button instead of mqtt message the sound plays.

Looking deeper into it, it seems that the way seeed_arduino_audio is handling the enabling and disabling of 		__enable_irq(); and __disable_irq(); in void AudioPlaySdRaw::play(void) > play_sd_raw.cpp or void AudioPlaySdWav::play(void) in play_sd_wav.cpp. are creating issues with other libraries that need to run in the main loop. 

My question is there a way to handle such events? for a process that could collide with any background process that pubsubclient is using?

Thank you and any suggestion would be appreciated!

**Comment by Cincinnatu** [comment]
Have you solved the problem now? If not, I will come back to check.

**Comment by gbernal** [comment]
Hi, No, I was not able to fix it. I ended up moving the project to a raspberry pi, but I do hope this gets fixed. As I would still like to use the Wio terminal instead.

**Comment by Cincinnatu** [comment]
Hi, I have reviewed this issue and it seems that the problem occurred due to interruptions being paused during playback. Have you tried using an RTOS to solve this issue?
