### ISSUE TITLE
SDTEST2.WAV file should be included

### ISSUE THREAD

**Issue by mcbpalisade** [Seeed-Studio/Seeed_Arduino_Audio#5]
Trying to get this going but I don't see the "SDTEST2.WAV" file that should be included on the SD card for "Play Music".  Not sure what it needs, would be nice if it was included somewhere.  Thanks

**Comment by Cincinnatu** [comment]
Hello, has this issue been resolved? If not, please provide more information.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
